//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication24.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jobsEntities1 : DbContext
    {
        public jobsEntities1()
            : base("name=jobsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_jobLinks> tb_jobLinks { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<PostItem> PostItems { get; set; }
        public virtual DbSet<JobPost> JobPosts { get; set; }
    }
}
