//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication24.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPost
    {
       
    }
}
namespace WebApplication24.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class JobPost
    {
        public string OfficialNotificationPath { get; set; }


        public int Id { get; set; }
        public string Department { get; set; }
        public System.DateTime LastDate { get; set; }
        public System.DateTime AdvertisementDate { get; set; }
        public string Location { get; set; }
        public string OfficialNotification { get; set; }
        public string NO_Post { get; set; }
        public Nullable<System.Guid> UniqueId { get; set; }
        public string mode { get; set; }
        public string StateName { get; set; }
        public string min_Age { get; set; }
        public string max_Age { get; set; }




        [NotMapped]
        public List<PostItemLIST> Posts { get; set; }
        [NotMapped]
        public List<SectionItem> Sections { get; set; } // for dynamic checkbox + textbox
        [NotMapped]
        public List<FEELIST> FEELIST { get; set; }

    }
    public class FEELIST
    {
        public string SC_ST_PwD_Ex_Serviceman { get; set; }

        public string General_OBC_EWS { get; set; }

        public string For_Girls { get; set; }
    }
    public class SectionItem
    {
        public bool IsChecked { get; set; }

        public string Label { get; set; }

        public string Text { get; set; }
    }
    public class PostItemLIST
    {
        public string PostName { get; set; }
        public string NoOfPosts { get; set; }
        public string Qualification { get; set; }
        public string Salary { get; set; }
    }
}
